apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd-v2
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: httpd
    repoURL: https://github.com/virtapp/deployment.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

