kubectl create secret docker-registry regcred -n centerity \
--docker-server=https://registry.gitlab.com/centerity/devops \
--docker-username=REVWT1BTLVRPS0VOLTE= \
--docker-password=cnlUZG55cVlzSG0xSGtzVV9YSlc=  \
--docker-email=yevgenis@centerity.com
