{{- if eq .Values.architecture "high-availability" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "influxdb.fullname" . }}-headless
  labels: {{- include "influxdb.labels" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if (.Values.service.rcpPort) }}
    - port: {{ .Values.service.rcpPort }}
      targetPort: rcp
      protocol: TCP
      name: rcp
    {{- end }}
  selector: {{- include "influxdb.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
{{- end }}
